name: bite_trace
description: The best food tracking app.
publish_to: "none"

version: 0.3.0+8

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  amplify_api: ^1.7.0
  amplify_auth_cognito: ^1.7.2
  amplify_authenticator: ^1.5.4
  amplify_flutter: ^1.7.0
  auto_route: ^7.8.0
  barcode_scan2: ^4.2.4
  dio: ^5.3.2
  fl_chart: ^0.66.2
  flex_color_scheme: ^7.2.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.4.1
  home_widget: ^0.4.1
  hooks_riverpod: ^2.3.7
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  logger: ^2.0.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.2
  openfoodfacts: ^3.4.0
  pedometer: ^4.0.1
  riverpod: ^2.3.6

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  lint: ^2.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

